name: Deploy Project to Our Servers

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: FTP Deployment to Client Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # ➤ Deploy to Client Server
      - name: Deploy to Client Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 31.97.86.127
          username: backend_ftp
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          passive: true
