name: Deploy Private GitHub repository to client server
on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 31.97.86.127
          username: backend_ftp
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          security: loose
          local-dir: ./
          server-dir: /
